# permissions for end users to view scheduledbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduledbackup-viewer-role
rules:
- apiGroups:
  - postgresql.k8s.2ndq.io
  resources:
  - scheduledbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgresql.k8s.2ndq.io
  resources:
  - scheduledbackups/status
  verbs:
  - get
