blank_issues_enabled: false
contact_links:
  - name: Open discussions
    url: https://github.com/cloudnative-pg/cloudnative-pg/discussions
    about: Please ask and answer questions here.
  - name: Slack chat
    url: https://github.com/cloudnative-pg/cloudnative-pg?tab=readme-ov-file#communications
    about: Please join the slack channel and interact with our community
