apiVersion: postgresql.cnpg.io/v1
kind: Subscription
metadata:
  name: subscription-sample
spec:
  name: sub
  dbname: app
  publicationName: pub
  cluster:
    name: cluster-sample-dest
  externalClusterName: cluster-sample
status:
  applied: false
