apiVersion: postgresql.cnpg.io/v1
kind: Publication
metadata:
  name: publication-sample
spec:
  name: pub
  dbname: app
  cluster:
    name: cluster-sample
  target:
    allTables: true
status:
  applied: false
