---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.15.0
  name: publications.postgresql.cnpg.io
spec:
  group: postgresql.cnpg.io
  names:
    kind: Publication
    listKind: PublicationList
    plural: publications
    singular: publication
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .spec.cluster.name
      name: Cluster
      type: string
    - jsonPath: .spec.name
      name: PG Name
      type: string
    - jsonPath: .status.ready
      name: Ready
      type: boolean
    - description: Latest error message
      jsonPath: .status.error
      name: Error
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: Publication is the Schema for the publications API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: PublicationSpec defines the desired state of Publication
            properties:
              cluster:
                description: The corresponding cluster
                properties:
                  name:
                    default: ""
                    description: |-
                      Name of the referent.
                      This field is effectively required, but due to backwards compatibility is
                      allowed to be empty. Instances of this type with an empty value here are
                      almost certainly wrong.
                      TODO: Add other useful fields. apiVersion, kind, uid?
                      More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Drop `kubebuilder:default` when controller-gen doesn't need it https://github.com/kubernetes-sigs/kubebuilder/issues/3896.
                    type: string
                type: object
                x-kubernetes-map-type: atomic
              dbname:
                description: The name of the database
                type: string
                x-kubernetes-validations:
                - message: dbname is immutable
                  rule: self == oldSelf
              name:
                description: The name inside PostgreSQL
                type: string
                x-kubernetes-validations:
                - message: name is immutable
                  rule: self == oldSelf
              owner:
                description: The owner
                type: string
              parameters:
                additionalProperties:
                  type: string
                description: Parameters
                type: object
              publicationReclaimPolicy:
                default: retain
                description: The policy for end-of-life maintenance of this publication
                enum:
                - delete
                - retain
                type: string
              target:
                description: Publication target
                properties:
                  allTables:
                    description: All tables should be publicated
                    type: object
                  objects:
                    description: Just the following schema objects
                    items:
                      description: PublicationTargetObject is an object to publicate
                      properties:
                        schema:
                          description: The schema to publicate
                          type: string
                        tableExpression:
                          description: A list of table expressions
                          items:
                            type: string
                          type: array
                      type: object
                    type: array
                type: object
                x-kubernetes-validations:
                - message: allTables and objects are not compatible
                  rule: (has(self.allTables) && !has(self.objects)) || (!has(self.allTables)
                    && has(self.objects))
            required:
            - cluster
            - dbname
            - name
            type: object
          status:
            description: PublicationStatus defines the observed state of Publication
            properties:
              error:
                description: Error is the reconciliation error message
                type: string
              observedGeneration:
                description: |-
                  A sequence number representing the latest
                  desired state that was synchronized
                format: int64
                type: integer
              ready:
                description: Ready is true if the database was reconciled correctly
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
