
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.7.0
  creationTimestamp: null
  name: scheduledbackups.postgresql.cnpg.io
spec:
  group: postgresql.cnpg.io
  names:
    kind: ScheduledBackup
    listKind: ScheduledBackupList
    plural: scheduledbackups
    singular: scheduledbackup
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .spec.cluster.name
      name: Cluster
      type: string
    - jsonPath: .status.lastScheduleTime
      name: Last Backup
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: ScheduledBackup is the Schema for the scheduledbackups API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: 'Specification of the desired behavior of the ScheduledBackup.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
            properties:
              backupOwnerReference:
                default: none
                description: 'Indicates which ownerReference should be put inside
                  the created backup resources.<br /> - none: no owner reference for
                  created backup objects (same behavior as before the field was introduced)<br
                  /> - self: sets the Scheduled backup object as owner of the backup<br
                  /> - cluster: set the cluster as owner of the backup<br />'
                enum:
                - none
                - self
                - cluster
                type: string
              cluster:
                description: The cluster to backup
                properties:
                  name:
                    description: Name of the referent.
                    type: string
                required:
                - name
                type: object
              immediate:
                description: If the first backup has to be immediately start after
                  creation or not
                type: boolean
              schedule:
                description: The schedule follows the same format used in Kubernetes
                  CronJobs, see https://pkg.go.dev/github.com/robfig/cron#hdr-CRON_Expression_Format
                type: string
              suspend:
                description: If this backup is suspended or not
                type: boolean
            required:
            - schedule
            type: object
          status:
            description: 'Most recently observed status of the ScheduledBackup. This
              data may not be up to date. Populated by the system. Read-only. More
              info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
            properties:
              lastCheckTime:
                description: The latest time the schedule
                format: date-time
                type: string
              lastScheduleTime:
                description: Information when was the last time that backup was successfully
                  scheduled.
                format: date-time
                type: string
              nextScheduleTime:
                description: Next time we will run a backup
                format: date-time
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
