# This workflow adds support for custom "slash commands" in the CI/CD pipeline.
# It is triggered by comments made on pull requests.
#
# 1. If the comment starts with "/test"
#    it will trigger a 'slash-command-receiver' workflow, which in turn, will
#    trigger an execution of the E2E Test Suite.
#
# 2. If the comment starts with "/ok-to-merge", it will label the PR with
#    "ok to merge :ok_hand:"
#
# 3. If the comment starts with "/ready-to-test", it will label the PR with
#    "ready to test :elephant:" if the label was not already applied, or remove
#    the label if it was there already.
#
name: slash-command-dispatcher

on:
  issue_comment:
    types: [created]

jobs:
  chatops-dispatcher:
    if: |
        github.event.issue.pull_request &&
        (
          startsWith(github.event.comment.body, '/test') ||
          startsWith(github.event.comment.body, '/ok-to-merge') ||
          startsWith(github.event.comment.body, '/ready-to-test')

        )
    runs-on: ubuntu-20.04
    steps:
      - name: Run E2E on CNPG
        uses: peter-evans/slash-command-dispatch@v3
        if: ${{ startsWith(github.event.comment.body, '/test') }}
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          issue-type: pull-request
          permission: write
          commands: |
            test
          static-args: |
            test_level=4
            depth=push
            plugin=false
            log_level=info

      - name: Add "ok to merge :ok_hand:" label to CNPG PR
        uses: actions-ecosystem/action-add-labels@v1.1.3
        if: ${{ startsWith(github.event.comment.body, '/ok-to-merge') }}
        with:
           github_token: ${{ secrets.REPO_GHA_PAT }}
           labels: "ok to merge :ok_hand:"

      - name: Remove "ready to test :elephant:" label if exists
        uses: actions-ecosystem/action-remove-labels@v1.3.0
        if: |
          startsWith(github.event.comment.body, '/ready-to-test')
        with:
          github_token: ${{ secrets.REPO_GHA_PAT }}
          labels: "ready to test :elephant:"

      - name: Add "ready to test :elephant:" label to CNPG PR
        uses: actions-ecosystem/action-add-labels@v1.1.3
        if: startsWith(github.event.comment.body, '/ready-to-test')
        with:
           github_token: ${{ secrets.REPO_GHA_PAT }}
           labels: "ready to test :elephant:"