# Create a tag when a PR on a release/v* branch is merged
name: release-tag

on:
  pull_request:
    types:
      - closed
    branches:
      - release-*
      - main
    paths:
      - 'pkg/versions/versions.go'

permissions: read-all

jobs:
  tag:
    runs-on: ubuntu-24.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      -
        name: Create tag
        if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/v')
        uses: christophebedard/tag-version-commit@57ffb155fc61c8ab098fcfa273469b532c1d4ce7 # v1.7.0
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          version_regex: '^Version tag to ([0-9]+\.[0-9]+\.[0-9]+(?:-[a-z][0-9a-z]*)?)'
          version_tag_prefix: v
          dry_run: false
