# Verify if a pull request contains the labels required to enable the merge button.
name: require-labels

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

env:
  REPO_TOKEN:  ${{ secrets.GITHUB_TOKEN }}

jobs:
  require-labels:
    name: Require labels
    runs-on: ubuntu-22.04
    steps:
      - name: Require labels
        uses: docker://agilepathway/pull-request-label-checker:v1.6.24
        with:
          any_of: "ok to merge :ok_hand:"
          none_of: "do not merge"
          repo_token: ${{ env.REPO_TOKEN }}
