name: spellcheck-woke
on:
  push:
  workflow_dispatch:

jobs:

  # Check code for non-inclusive language
  woke:
    name: Run woke
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: woke
        uses: get-woke/woke-action@b2ec032c4a2c912142b38a6a453ad62017813ed0 # v0
        with:
          # Cause the check to fail on any broke rules
          fail-on-error: true

  # Enforce en-us spell check
  spellcheck:
    name: Run spellcheck
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@23dc186319866e1de224f94fe1d31b72797aeec7 # 0.48.0
