name: Sync API

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  trigger-sync:
    if: ${{ github.repository == 'cloudnative-pg/cloudnative-pg' }}
    runs-on: ubuntu-latest
    steps:
      - name: Invoke repository dispatch
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: cloudnative-pg/api
          event-type: sync-api
